--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t abdalluhmostafa/codepipline-node ."
      - "docker tag abdalluhmostafa/codepipline-node abdalluhmostafa/codepipline-node:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push abdalluhmostafa/codepipline-node:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
artifacts:
    files:
      - '**/*'
version: 0.1

