--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t node-server ."
      - "docker tag node-server node-server:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
artifacts:
    files:
      - '**/*'
version: 0.1

